# Generated by Django 6.0.6 on 2026-07-01 14:34

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KumaMonitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('kuma_monitor_id', models.CharField(max_length=80, unique=True)),
                ('service_key', models.SlugField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_available', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['is_available'], name='status_kuma_is_avai_e32804_idx')],
            },
        ),
        migrations.CreateModel(
            name='StatusPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_slug', models.CharField(max_length=40)),
                ('slug', models.SlugField(default='main', max_length=80)),
                ('title', models.CharField(max_length=160)),
                ('description', models.TextField(blank=True)),
                ('logo_url', models.URLField(blank=True)),
                ('back_link_label', models.CharField(blank=True, max_length=80)),
                ('back_link_url', models.URLField(blank=True)),
                ('is_visible', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['site_slug', 'slug'],
                'indexes': [models.Index(fields=['site_slug', 'slug', 'is_visible'], name='status_stat_site_sl_602e98_idx')],
                'constraints': [models.UniqueConstraint(fields=('site_slug', 'slug'), name='status_one_page_slug_per_site')],
            },
        ),
        migrations.CreateModel(
            name='StatusPageService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(blank=True, max_length=120)),
                ('position', models.PositiveIntegerField(default=0)),
                ('is_visible', models.BooleanField(default=True)),
                ('monitor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='status_page_selections', to='status.kumamonitor')),
                ('status_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selected_services', to='status.statuspage')),
            ],
            options={
                'ordering': ['position', 'monitor__name'],
            },
        ),
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180)),
                ('severity', models.CharField(choices=[('minor', 'Minor'), ('major', 'Major'), ('critical', 'Critical')], default='minor', max_length=20)),
                ('phase', models.CharField(choices=[('investigating', 'Investigating'), ('identified', 'Identified'), ('monitoring', 'Monitoring'), ('resolved', 'Resolved')], default='investigating', max_length=20)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('summary', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incidents', to='status.statuspage')),
                ('affected_services', models.ManyToManyField(blank=True, related_name='incidents', to='status.statuspageservice')),
            ],
            options={
                'ordering': ['-started_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='IncidentUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phase', models.CharField(choices=[('investigating', 'Investigating'), ('identified', 'Identified'), ('monitoring', 'Monitoring'), ('resolved', 'Resolved')], max_length=20)),
                ('message', models.TextField()),
                ('published_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updates', to='status.incident')),
            ],
            options={
                'ordering': ['published_at', 'created_at'],
                'indexes': [models.Index(fields=['incident', 'published_at'], name='status_inci_inciden_7de2ba_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='statuspageservice',
            index=models.Index(fields=['status_page', 'position'], name='status_stat_status__4be0f4_idx'),
        ),
        migrations.AddConstraint(
            model_name='statuspageservice',
            constraint=models.UniqueConstraint(fields=('status_page', 'monitor'), name='status_one_monitor_per_page'),
        ),
        migrations.AddIndex(
            model_name='incident',
            index=models.Index(fields=['status_page', 'phase', 'started_at'], name='status_inci_status__2867f3_idx'),
        ),
        migrations.AddIndex(
            model_name='incident',
            index=models.Index(fields=['status_page', 'resolved_at'], name='status_inci_status__f5fe11_idx'),
        ),
    ]
