# Generated by Django 6.0.6 on 2026-07-01 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='kumamonitor',
            name='kuma_monitor_type',
            field=models.CharField(blank=True, editable=False, max_length=40),
        ),
    ]
