# Generated by Django 6.0.6 on 2026-07-04 20:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0002_kumamonitor_kuma_monitor_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='KumaMonitorDailyUptime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField()),
                ('samples_count', models.PositiveIntegerField(default=0)),
                ('up_count', models.PositiveIntegerField(default=0)),
                ('down_count', models.PositiveIntegerField(default=0)),
                ('unknown_count', models.PositiveIntegerField(default=0)),
                ('max_consecutive_down', models.PositiveIntegerField(default=0)),
                ('current_consecutive_down', models.PositiveIntegerField(default=0)),
                ('last_heartbeat_at', models.DateTimeField(blank=True, null=True)),
                ('last_status', models.CharField(choices=[('operational', 'Healthy'), ('degraded', 'Degraded'), ('down', 'Unavailable'), ('unknown', 'Unknown')], default='unknown', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('monitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_uptime', to='status.kumamonitor')),
            ],
            options={
                'ordering': ['monitor', 'day'],
                'indexes': [models.Index(fields=['monitor', 'day'], name='status_kuma_monitor_af99c4_idx')],
                'constraints': [models.UniqueConstraint(fields=('monitor', 'day'), name='status_one_daily_uptime_per_monitor_day')],
            },
        ),
    ]
